[project]
name = "vision-pro"
version = "0.1.0"
description = "Webcam-based computer vision application"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "opencv-python>=4.11.0.86",
    "mediapipe==0.10.14",
    "numpy>=2.4.0",
    "pycaw>=20240210",
    "comtypes>=1.4.1",
]
